/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/access-grants': RouteRecordInfo<'/admin/access-grants', '/admin/access-grants', Record<never, never>, Record<never, never>>,
    '/admin/api-keys': RouteRecordInfo<'/admin/api-keys', '/admin/api-keys', Record<never, never>, Record<never, never>>,
    '/admin/artefacts/': RouteRecordInfo<'/admin/artefacts/', '/admin/artefacts', Record<never, never>, Record<never, never>>,
    '/admin/artefacts/[id]': RouteRecordInfo<'/admin/artefacts/[id]', '/admin/artefacts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/artefacts/': RouteRecordInfo<'/artefacts/', '/artefacts', Record<never, never>, Record<never, never>>,
    '/artefacts/[id]': RouteRecordInfo<'/artefacts/[id]', '/artefacts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
