/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessGrantsSection: typeof import('./src/components/admin/access-grants-section.vue')['default']
    ApiKeysSection: typeof import('./src/components/admin/api-keys-section.vue')['default']
    ArtefactAdmin: typeof import('./src/components/artefact-admin.vue')['default']
    ArtefactMetadata: typeof import('./src/components/artefact-metadata.vue')['default']
    DefaultLayout: typeof import('./src/components/default-layout.vue')['default']
    RemoteRegistriesSection: typeof import('./src/components/admin/remote-registries-section.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VjsfPatchReq: typeof import('./src/components/vjsf/vjsf-patch-req.vue')['default']
    VjsfPatchReqEn: typeof import('./src/components/vjsf/vjsf-patch-req-en.vue')['default']
    VjsfPatchReqFr: typeof import('./src/components/vjsf/vjsf-patch-req-fr.vue')['default']
  }
}
