/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNav: typeof import('./src/components/admin-nav.vue')['default']
    DefaultLayout: typeof import('./src/components/default-layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VjsfPatchReq: typeof import('./src/components/vjsf/vjsf-patch-req.vue')['default']
    VjsfPatchReqEn: typeof import('./src/components/vjsf/vjsf-patch-req-en.vue')['default']
    VjsfPatchReqFr: typeof import('./src/components/vjsf/vjsf-patch-req-fr.vue')['default']
  }
}
